import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/header/header";
import ReactQueryProvider from "@/providers/reaact-query-provider";
import ThemeChangeButton from "@/components/theme-change-button/theme-change-button";
import ScriptTheme from "@/helper/ScriptTheme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} suppressHydrationWarning>
        <ScriptTheme />
        <div className={"body-content-wrapper"}>
          <ReactQueryProvider>
            <Header />
            {children}
            <ThemeChangeButton />
          </ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
