export const chartList = [
  { song: "밤하늘의 별을", singer: "경서", chart: 1 },
  { song: "Ditto", singer: "NewJeans", chart: 2 },
  { song: "I AM", singer: "IVE", chart: 3 },
  { song: "사랑은 늘 도망가", singer: "임영웅", chart: 4 },
  { song: "TOMBOY", singer: "(G)I-DLE", chart: 5 },
  { song: "사건의 지평선", singer: "윤하", chart: 6 },
  { song: "Hype Boy", singer: "NewJeans", chart: 7 },
  { song: "LOVE DIVE", singer: "IVE", chart: 8 },
  { song: "우리들의 블루스", singer: "임영웅", chart: 9 },
  { song: "Next Level", singer: "aespa", chart: 10 },
  { song: "INVU", singer: "태연", chart: 11 },
  { song: "Attention", singer: "NewJeans", chart: 12 },
  { song: "그때 그 순간 그대로", singer: "WSG워너비", chart: 13 },
  { song: "취중고백", singer: "김민석", chart: 14 },
  { song: "Feel My Rhythm", singer: "Red Velvet", chart: 15 },
  { song: "Butter", singer: "BTS", chart: 16 },
  { song: "Steal The Show", singer: "Lauv", chart: 17 },
  { song: "ELEVEN", singer: "IVE", chart: 18 },
  { song: "POP!", singer: "나연 (TWICE)", chart: 19 },
  { song: "Drunken Confession", singer: "김나영", chart: 20 },
  { song: "Permission to Dance", singer: "BTS", chart: 21 },
  { song: "Shutdown", singer: "BLACKPINK", chart: 22 },
  { song: "눈이 오잖아", singer: "이무진", chart: 23 },
  { song: "Love Me Like This", singer: "NMIXX", chart: 24 },
  { song: "Polaroid Love", singer: "ENHYPEN", chart: 25 },
  { song: "Teddy Bear", singer: "STAYC", chart: 26 },
  { song: "ANTIFRAGILE", singer: "LE SSERAFIM", chart: 27 },
  { song: "그라데이션", singer: "10CM", chart: 28 },
  { song: "ASAP", singer: "STAYC", chart: 29 },
  { song: "모든 날, 모든 순간", singer: "폴킴", chart: 30 },
  { song: "Starlight", singer: "태일 (NCT)", chart: 31 },
  { song: "Yet To Come", singer: "BTS", chart: 32 },
  { song: "좋아좋아", singer: "조정석", chart: 33 },
  { song: "어떻게 이별까지 사랑하겠어", singer: "AKMU", chart: 34 },
  { song: "이제 나만 믿어요", singer: "임영웅", chart: 35 },
  { song: "Sugar Rush Ride", singer: "TXT", chart: 36 },
  { song: "Beautiful", singer: "Crush", chart: 37 },
  { song: "봄날", singer: "BTS", chart: 38 },
  { song: "마이웨이", singer: "임영웅", chart: 39 },
  { song: "밤이 무서워요", singer: "10CM", chart: 40 },
  { song: "Blue & Grey", singer: "BTS", chart: 41 },
  { song: "사랑이라 믿었던 것들은", singer: "이예준", chart: 42 },
  { song: "그대라는 사치", singer: "임창정", chart: 43 },
  { song: "너의 모든 순간", singer: "성시경", chart: 44 },
  { song: "도깨비불", singer: "aespa", chart: 45 },
  { song: "Boo", singer: "Seori", chart: 46 },
  { song: "Weekend", singer: "태연", chart: 47 },
  { song: "My Universe", singer: "Coldplay X BTS", chart: 48 },
  { song: "에잇", singer: "아이유 (Feat. SUGA)", chart: 49 },
  { song: "눈의 꽃", singer: "박효신", chart: 50 },
  { song: "Blueming", singer: "아이유", chart: 51 },
  { song: "봄사랑벚꽃말고", singer: "하이포, 아이유", chart: 52 },
  { song: "Love poem", singer: "아이유", chart: 53 },
  { song: "Celebrity", singer: "아이유", chart: 54 },
  { song: "아이와 나의 바다", singer: "아이유", chart: 55 },
  { song: "마음", singer: "아이유", chart: 56 },
  { song: "잊혀지지마", singer: "Crush", chart: 57 },
  { song: "그날들", singer: "김범수", chart: 58 },
  { song: "처음처럼", singer: "엠씨더맥스", chart: 59 },
  { song: "너였다면", singer: "정승환", chart: 60 },
];
